### ISSUE TITLE
DockerFile.RbuildEnv failed with:  The command '/bin/sh -c Rscript -e "devtools::install_version('forecast', version = '8.9', repos = "http://cran.us.r-project.org")" &&     rm -rf /tmp/*' returned a non-zero code: 1

### ISSUE THREAD

**Issue by tinghf** [seattleflu/incidence-mapper#120]
Bamboo job failed in test_dev after merging in from dev, bamboo run link: 
http://idm-bamboo:8085/browse/RSE-SEATFBRE-41

Per log below it seems to be caused by a bad quote in package install as follows: 

> Already on 'test_dev'
> WARNING! Using --password via the CLI is insecure. Use --password-stdin.
> WARNING! Your password will be stored unencrypted in /home/idm_bamboo_user/.docker/config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credentials-store
> 
> The command '/bin/sh -c Rscript -e "devtools::install_version('forecast', version = '8.9', repos = "http://cran.us.r-project.org")" &&     rm -rf /tmp/*' returned a non-zero code: 1
> make: *** [test-build-r-env] Error 1

**Comment by tinghf** [comment]
seems to be a double quote in double quote issue in RUN statement, validated work in my local environment after changing it to: 

> RUN Rscript -e "devtools::install_version('forecast', version = '8.9', repos = 'http://cran.us.r-project.org')" && \
>     rm -rf /tmp/*
>

**Comment by famulare** [comment]
Thanks Tony.  Yeah, the easy fix is to single quote inside the command since R treats single and double quotes the same. Can you fix these and put in a PR for @devclinton to review?

**Comment by tinghf** [comment]
Yes Mike, I already has the fix, I'm just waiting for my previous PR to get merged before I submitted another minor one specifically for this issue.

**Comment by tinghf** [comment]
The fix is submitted to test_dev, and should be propagate to dev once following PR is merged: 
pr to dev in #116.

Will close once it got into dev branch.

**Comment by tinghf** [comment]
got merged in dev branch, closing.
