### ISSUE TITLE
Incorporate census demographic data

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#20]
We need to pull in census demographic data to move toward understanding denominators and eventually producing post-stratified incidence estimates for different population groupings, instead of just the latent field estimate.

This will require additional data curation and data-model integration code.

**Comment by tsibley** [comment]
We may be able to build off the work of censusreporter.org and use their code for loading ACS data into Postgres: https://github.com/censusreporter/census-postgres

**Comment by grhuynh** [comment]
@tsibley I was thinking of using tidycensus https://walkerke.github.io/tidycensus/ and the census API to directly get the data into R. Do you think we should also have an option to access via censusreporter as above?

**Comment by tsibley** [comment]
@grhuynh That seems good too! :-) I just wanted to note an option if we wanted to have a local copy of the data.

**Comment by famulare** [comment]
@grhuynh Does https://github.com/seattleflu/incidence-mapper/blob/master/dbViewR/R/addCensusData.R close this ticket?  If so, can you close it out with a brief comment explaining what the function does?

**Comment by grhuynh** [comment]
use tidycensus to get census data and merge with input dataset https://github.com/seattleflu/incidence-mapper/blob/master/dbViewR/R/addCensusData.R
