### ISSUE TITLE
Use ISO weeks for international consistency

### ISSUE THREAD

**Issue by tsibley** [seattleflu/incidence-mapper#26]
Great to see the move to binning by week! I think that we should be using ISO week definitions and the standard `2019-W02` format not `2019_W02`. ISO weeks are slightly different from CDC weeks, [as described most succinctly](https://epiweeks.readthedocs.io/en/latest/):

> The US CDC defines epidemiological week (known as MMWR week) as seven days beginning with Sunday and ending with Saturday. The WHO defines epidemiological week, based on ISO week, as seven days beginning with Monday and ending with Sunday. In either case, the end of the first epidemiological week of the year by definition must fall at least four days into the year. Most years have 52 epidemiological weeks, but some have 53.

It's my understanding that ISO weeks are used more widely around the world, and just like we use the metric system in science, it seems we should use international datetime standards as well.

Changing [this line](https://github.com/seattleflu/incidence-mapper/blob/88f63f1dd16b2f183dd86b5d5c4c3e6f340f4cf0/dbViewR/R/selectFromDB.R#L74) to do:

```
db$iso_week <- format(db$encountered_date, "%G-W%V")
```

will use the datetime (`strftime`) formatting codes for ISO week year and week number.

**Comment by tsibley** [comment]
The research database can also easily provide ISO weeks directly, which may be useful for a consistency of data transforms standpoint.

**Comment by famulare** [comment]
I'd rather get it from the database for sure.

**Comment by famulare** [comment]
If I can assume it'll be in the database fairly soon, I'll add it to the simulated_database and simplify the code to assume it'll be there.

**Comment by tsibley** [comment]
Got it. I can add it to the database today or tomorrow.

**Comment by tsibley** [comment]
The database view now has a `encountered_week` column.

**Comment by famulare** [comment]
dbViewR changed to assume encountered_week is available in the database in a83d2758687941d9a8ebb1675b583d5a20602c23.  Change will migrate to master when merging connect-to-real-data
