### ISSUE TITLE
reduce disk footprint of large RDS model saves

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#30]
The geoid x time inla model objects can take up to 2GB on disk when saved as RDS.  There's plenty of inefficiencies and redundancies in the model object right now, so we should try to shrink it, eventually.

**Comment by devclinton** [comment]
@famulare I might have resolved this in my branch. My RDS files are now around ~21mb on average from the folder you gave me vs 81 at their original size. I switched to compression at level 9. It is slower during the save but that should be worth the trade off. You can take a look at relevant code at https://github.com/seattleflu/incidence-mapper/blob/load-save-model/modelServR/R/saveModel.R#L136

**Comment by famulare** [comment]
has been incorporated into modelServR
