### ISSUE TITLE
New issue with permissions in RStudio server

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#36]
As of this evening, when trying to open a project in Rstudio, I get an error: 
![image](https://user-images.githubusercontent.com/10134931/56548460-fedb4b00-6534-11e9-99d9-fab07820d4c2.png).  

This started before the rebuild of #33, so I have no idea why.   It could be a VPN thing as I've only tried from home today, but I don't see why....

**Comment by devclinton** [comment]
When you restarted RStudio via Docker, did you run the following sequence?

`export UID=$UD
docker-compose up -d`

Also, the following should work as well
`UID=$UID docker-compose up -d`

The docker image has user-level permissions and the *export UID=$UID* or the *UID=$UID* portions of the commands above pass the current user is to the image to properly map the permissions between host and container. My best guess is you ran without doing the export first. If you open a terminal up and then 
`
cd /home/rstudio/seattle_flu
touch test_permissions
`
If the touch command fails, it is the UID issues.
If the above commands succeeds, then the container permissions are not the issue. In that case, it could be the project file has the wrong permissions. I would check the project by doing the following on your host(not in the container). The first command could have wrong path but basically navigate to your git checkout through ssh. 
`
cd ~/incidence-mapper/u/dbViewR
ls -al
`
![image](https://user-images.githubusercontent.com/208629/56599955-86b06c00-65ac-11e9-8969-2a4d8f387f39.png)

If the project file is not owned by you, run the following. Replace user with the your linux user name. I usually use the one from the ls -al output. 
`
sudo chown <user>:<group> dbViewR.Rproj
`

**Comment by famulare** [comment]
Yep, forgot `export UID=$UD docker-compose up -d`.
