### ISSUE TITLE
Should masterShapeDB point to seattleflu/geo-json?

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#4]
We need to agree on shapes, but that requires choosing a valid domain.  See https://github.com/seattleflu/seattle-geojson/issues/1 for discussion.

**Comment by tsibley** [comment]
My 2¢: I think I need our geospatial shapes in the database anyway, so that location could become the authority for shape data if we wanted.

**Comment by grhuynh** [comment]
I'll try to connect the masterSpatialDB to seattleflu/geo-json, assuming those files are not being further modified?

**Comment by famulare** [comment]
Great!  They are fixed for now. They might change in the future, but the format should remain geojson. The CRA_NAME and NEIGHBORHOOD_... are the least stable because they are only defined for Seattle city limits right now.  In principle, we can expand those, but as far as I can tell we have to get neighborhood-level shapes from each town, as I can't find a central repository.

**Comment by famulare** [comment]
@grhuynh If/when you do that, please branch off of master, and when you think it all works, put in a pull request.

**Comment by famulare** [comment]
Another comment. I just noticed that the seattle-geojsons are literally seattle only.  So, keep an option to point to the original shapefiles too, as those are all king county.  In May, we collectively should expand the curated scope and how we selectively access it: (see https://github.com/seattleflu/seattle-geojson/issues/1#issue-428850776)
