### ISSUE TITLE
dbConnect throws new error on IDMPPWK....

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#40]
On IDMPPWK..., running this block

```
> Sys.setenv(PGSERVICEFILE = file.path(credentials_path, ".pg_service.conf"),
                PGPASSFILE    = file.path(credentials_path, ".pgpass"))

>     rawData <- DBI::dbConnect(RPostgres::Postgres(), service = "seattleflu-production")
```
yields this error:
```
WARNING: password file "/home/rstudio/seattle_flu/.pgpass" has group or world access; permissions should be u=rw (0600) or less
Error in connection_create(names(opts), as.vector(opts)) : 
  fe_sendauth: no password supplied
```

.pgpass and pg_service.conf are in the correct directory, and the script here does work: https://github.com/seattleflu/incidence-mapper/blob/c1a12512fa61d9c07953b588019efe66a8d5192a/dbViewRSQL/selectFromDB_SQL.R#L68

**Comment by tsibley** [comment]
Postgres requires that password files have secure permissions or it won't use them, so you'll need to make sure that in the container the permissions are at most `u=rw` with `chmod u=rw,go= /home/rstudio/seattle_flu/.pgpass`. (This is similar to ssh requiring secure permissions on `~/authorized_keys` file.)

**Comment by tsibley** [comment]
I'm not sure off the top of my head and with your setup where the most appropriate place to adjust permissions is, but @devclinton can help I expect.

**Comment by devclinton** [comment]
@famulare Run the following command from within the directory you have your .pgpass(it should work inside or outside container) 

```
chmod -v u=rw,og= .pgpass
```

**Comment by famulare** [comment]
That took care of it. Thanks!
