### ISSUE TITLE
how do we want to address array factor data, like `pathogen = {Flu_A_H1, RSV}`?

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#44]
For fields like `race` or (importantly) `pathogen`, multiple values are possible.  The easy thing to do is to give array entries their own category, as in `pathogen = {Flu_A_H1, RSV}` is a third outcome category, but this won't always make sense for all analyses.  Need to think through use cases...

**Comment by tsibley** [comment]
Let me know what changes we might make to the database side of things to accommodate the modeling.

**Comment by famulare** [comment]
The database changes made this issue irrelevant.
