### ISSUE TITLE
WHERE ... IN statements to model requests are required for pathogen field

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#53]
Is it possible to get `IN` statements into the model lookup soon?

(Bad JSON, but like)
```
{
 "model_type": "smooth",
 "observed": [
   "pathogen": ["all"],
   "residence_cra_name",
   "site_type"
 ]
}
```

This is deeply important for `pathogen`, but is optional for now on any other field, as it's part of the deployed model definition: https://github.com/seattleflu/incidence-mapper/blob/8063cfe82279edbbe1584ce17bbbdf6319551584/incidenceMapR/buildModelsForDeployment.R#L40

**Comment by devclinton** [comment]
This and spatial_domain are both added now
