### ISSUE TITLE
Add "spatial_domain" to model definition and lookup

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#56]
I realize now we need to be explicit about the spatial domain of the models (like `seattle`, `king_county`, or `wa_state`), but this isn't being tracked anywhere.   

The domain has to be added to `modelDefinitions`, and extracted/referenced in `modelServR` where appropriate, mirroring what we did in #53.

**Comment by devclinton** [comment]
When you add this to the definition let me know and I will update get model id in both python and R

**Comment by famulare** [comment]
I suspect part of the problem with #61 is that the human readable name doesn't seem to exactly match the query json, but I'm not 100% sure that's true and if true why.
