### ISSUE TITLE
returnModel needs to be less fragile

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#6]
the model lookup operation in returnModel is very fragile as it requires an exact string match for a JSON query.  This should be replaced with a proper artifact management database.  Changes here are coupled with saveModel: https://github.com/seattleflu/incidence-mapper/issues/5

**Comment by devclinton** [comment]
Currently in progress. I am looking at moving all models to be stored in a postgres DB and then served using a simple API(wrapped around https://github.com/PostgREST/postgrest)
