### ISSUE TITLE
API bugs

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#61]
In the swagger ui, this query returns a valid csv but an empty json
```
{
  "model_type": "inla",
  "observed": [
    "residence_census_tract",
    "site_type",
    "pathogen",
    "flu_shot",
    "sex",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

**Comment by famulare** [comment]
But this query returns valid csv and json
```
{
  "model_type": "inla",
  "observed": [
    "residence_puma",
    "site_type",
    "pathogen",
    "flu_shot",
    "sex",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

**Comment by famulare** [comment]
This works too:
```
{
  "model_type": "inla",
  "observed": [
    "residence_cra_name",
    "site_type",
    "pathogen",
    "flu_shot",
    "sex",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

**Comment by famulare** [comment]
The one that failed is the biggest CSV, (and also most likely to have a nan or inf value, which shouldn't matter, but still).

**Comment by famulare** [comment]
I also haven't found an `inla_latent` call that works.  I believe each of the above models should have a latent partner, and I've tried to reproduce what I can see from within the modelDB.tsv, but haven't gotten an inla_latent query to work yet.

Example I think should work:
```
{
  "model_type": "inla_latent",
  "observed": [
    "residence_cra_name",
    "pathogen",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```
possibly without `"observed":"pathogen"`

Returns
```
  "error": "Could not find the model with the id dcf443667ceb4909a3163864f720309d from query string: {\"model_type\": \"inla_latent\", \"observed\": [\"residence_cra_name\", \"pathogen\", \"encountered_week\"], \"pathogen\": [\"all\"]}"
```

**Comment by devclinton** [comment]
I am going to take a look at this evening/ tomorrow. I suspect this is partially some of the error handling. My guess is I stream the model output before it is ready. That would make it appear successful but possible empty or truncated. I have an idea how to handle this. 

On the human readable name, I need to make some updates. I think now the pathogen is most likely missing. 

I will first start with latent. I know I had tested an older model that was a latent but that is before the recent updates

**Comment by devclinton** [comment]
Also, as a side note, thanks for this list. If we can possibly maintain a list of models I would like to add a production system sanity test to catch any issues that arise can be caught early once all this is resolved

**Comment by jameshadfield** [comment]
@devclinton -- thanks for setting up the swagger page :) 
Just a heads up that the

**Comment by jotasolano** [comment]
Adding to this, (unless I'm doing something wrong), this query is also returning an error:

```
{
  "model_type": "inla",
  "observed": [
    "residence_puma",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

`{
  "error": "Could not find the model with the id c1ccad065fb9028d502f42bfc3c65974 from query string: {\"model_type\": \"inla\", \"observed\": [\"residence_puma\", \"encountered_week\"], \"pathogen\": [\"all\"]}"
}`

**Comment by devclinton** [comment]
I have tested the following models and they are working now 
```
{
  "model_type": "inla_latent",
  "observed": [
    "residence_cra_name",
    "pathogen",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

```
{
  "model_type": "inla_observed",
  "observed": [
    "residence_puma",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```

```
{
  "model_type": "inla_observed",
  "observed": [
    "residence_cra_name",
    "site_type",
    "pathogen",
    "flu_shot",
    "sex",
    "encountered_week"
  ],
  "pathogen": [
    "all"
  ]
}
```
I am tested other models
You can check available models at 

http://40.112.165.255/v1/ui/#!/generic95model/seattle_flu_incidence_mapper_generic_models_read_all


I still need to update example. Next public update the Swagger  will have a working default example as well

**Comment by devclinton** [comment]
I believe this is resolved. Closing now after the last API update
