### ISSUE TITLE
Bug in csv to json on server: missing keys when value = Inf

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#70]
![image](https://user-images.githubusercontent.com/10134931/58132511-51606380-7bd6-11e9-849d-a95f3b3b9c4f.png)

@jotasolano caught an unexpected behavior described [here](https://seattle-flu-study.slack.com/archives/CFAEU7MQV/p1558474356066600?thread_ts=1558462672.045600&cid=CFAEU7MQV).  JSON output is missing keys when the value is `Inf`.  This is unexpected behavior. 

With enough data, `Inf` values shouldn't occur, but this edge case will likely remain relevant during prototyping, so we should figure it out when we clean up the alpha deployment.

**Comment by devclinton** [comment]
My guess is the serializing is throwing a fit over the Inf value as non serializable similar to how it does with NaNs. I should be able to resolve this by tomorrow

**Comment by devclinton** [comment]
I have this bug fixed. I need to deploy. I am automated the deploy and working cross-training another user so the deploy is taking a bit longer than expected.
