### ISSUE TITLE
Create clear git branching guidelines for developers along with milestones

### ISSUE THREAD

**Issue by devclinton** [seattleflu/incidence-mapper#82]
We need to clearly document our expected git process for branching, milestones, etc. We need to also ensure all developers understand the document and are given support to ensure it is being followed.

In addition, master branch should be locked down in the future.

**Comment by famulare** [comment]
I updated master on Friday with something cleaned up from the summer chaos, but I haven't finished scientific validation yet.  I also put commit restrictions on it, so that either you or I has final approval.  I'll still defer to you on how this should go forward.
