### ISSUE TITLE
Reconnect with Hutch team to discuss API and/or data hand-off

### ISSUE THREAD

**Issue by famulare** [seattleflu/incidence-mapper#83]
We had a recent discussion about whether we should continue to build on a server at IDM, or if the model store should move over to Fred Hutch.  This conversation isn't resolved, but should be had soon.

The core issue is that
1) we originally proposed to serve models from IDM because I expected to be using live function calls for model predictions. But this was not the right way to go, and we are now serving cached model outputs, and expect to continue doing so. Thus, IDM could move to shipping models to the model store only, and the api from the store could be managed by the Hutch team, putting all web API development in one house.
2) But the models may also get called this year from a self-testing app and not just from the viz website.  And so continuing to use the model server with its API could be useful for maintaining modularity. 

There are other issues with either approach I'm sure, but I want to flag this developer discussion now before we invest much more in hardening the IDM model server.

**Comment by kairstenfay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reconnect with Hutch team to discuss API and/or data hand-off](https://trello.com/c/muGbmXq0/161-reconnect-with-hutch-team-to-discuss-api-and-or-data-hand-off)

**Comment by tsibley** [comment]
@famulare or @devclinton, as a way to start thinking about this more concretely, could one of you provide us with an example or two of the stuff in the model store? My understanding is that it's essentially a tabular dataframe, and I'd like to get a better sense of what's there. I could likely do this from reading the code more closely, but an example or two would be easier/quicker, I think.

@joverlee521 I tagged you in this issue to keep you in the loop as well.

**Comment by devclinton** [comment]
These are a bit old but should suffice for an overview of both data structures. The CSV is the cached model output where the RDS is the built R model. 

https://idmod-my.sharepoint.com/:u:/g/personal/ccollins_idmod_org/EacagxCc7aNHjK25L1O7qwoBjv3XqmWRNmYoliKOpnNOqA?e=nmFc1b

**Comment by devclinton** [comment]
Assume this ticket is closed. I think it is but if not, we can reopen later
