### ISSUE TITLE
Documentation for API Service cannot be found

### ISSUE THREAD

**Issue by kairstenfay** [seattleflu/incidence-mapper#84]
The following link from the `api_service` README is broken:

https://institutefordiseasemodeling.github.io/Seattle-Flu-Incidence-Mapper

Source: https://github.com/seattleflu/incidence-mapper/tree/master/api_service

Where can I find the documentation?

**Comment by devclinton** [comment]
You are correct, the current readme is incomplete. The readme for the API was neglected a bit toward the end of last release. I will be updated that sometime in the next few days with more complete documentation.

Until then, the following should suffice in using the API.
The best source of documentation on the API service at the moment is the swagger page. http://40.112.165.255/v1/ui. You can use the GET /generic_models to get a list of valid models(and their respective query strings). You can then use any of those query string in the POST /query api. 

Do you need documentation on how to run the API service locally as well or is API use enough?

**Comment by kairstenfay** [comment]
I think this is plenty for me to get the API integrated with the Seattle Flu viz. Thank you!

**Comment by kairstenfay** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Connect IDM model output to viz prototype](https://trello.com/c/UQO8iyqB/136-connect-idm-model-output-to-viz-prototype)
