### ISSUE TITLE
Add a Cross-Origin Policy to the modelling API

### ISSUE THREAD

**Issue by kairstenfay** [seattleflu/incidence-mapper#86]
When trying to access the modelling API through my browser (localhost), I get
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://40.112.165.255/v1/query. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://40.112.165.255/v1/query. (Reason: CORS request did not succeed).
``` 

Please consider adding a CORS policy to whitelist everyone or add a few exceptions (localhost and the seattleflu website).

**Comment by devclinton** [comment]
This totally makes sense. I would prefer to go head and make a whitelist vs completely open.  I will add localhost and Seattle Flu site for now. We can look at additional whitelisted sites later.

**Comment by devclinton** [comment]
@kairstenfay could you take a look at the newest update to see if this is resolve for you? I have a very open policy at the moment but later we will gradually restrict it.

**Comment by kairstenfay** [comment]
Wonderful! This resolves the issue I was running into with the genomic-incidence-tracker. Thank you.
